version: '3.3'
services:
  db:
    image: mysql
    # restart: always
    environment:
      MYSQL_DATABASE: 'activiti'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dev-db:/var/lib/mysql

 
  redis:
    # 镜像名称以及版本号
    image: redis
    # 失败后总是重启
    # restart: always
    # 自定义容器名
    container_name: docker_redis
    # 文件夹以及文件映射
    volumes:
      - redis-data:/data
      # 注意这里需要先  /usr/local/app/redis/conf  新建redis.conf文件  redis.conf文件可从http://www.redis.cn/下载
      # - /usr/local/app/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      # - /usr/local/app/redis/logs:/logs
    # command:
      # 以配置文件的方式启动 redis.conf
      # redis-server /usr/local/etc/redis/redis.conf
    ports:
      # 端口号
      - '127.0.0.1:6379:6379'
 

# Names our volume
volumes:
  dev-db:
  redis-data:
